CREATE TABLE IF NOT EXISTS usuario (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  senha TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS projeto (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL UNIQUE,
  descricao TEXT NOT NULL,
  data_inicio DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS tarefa (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  titulo TEXT NOT NULL,
  descricao TEXT NOT NULL,
  status TEXT NOT NULL,
  data_criacao DATETIME NOT NULL,
  data_prazo DATETIME,
  projeto_id INTEGER NOT NULL,
  usuario_id INTEGER NOT NULL,
  FOREIGN KEY (projeto_id) REFERENCES projeto(id) ON DELETE CASCADE
  FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
);



